[build]
  base = "frontend"
  publish = "build"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.22"
  REACT_APP_API_URL = "https://api.example.org"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
